development:
  adapter: postgresql
  encoding: utf8
  database: gmap_development
  pool: 5
  username: postgres 
  password: postgres

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: gmap_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: gmap_production
  pool: 15
  username: localhost
  password:

cucumber:
  <<: *TEST
