Place.create! title: "Bus Stop 1", address: "405 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 2", address: "265 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 3", address: "200 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 4", address: "33 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 5", address: "59 Ly Thai Tong, Da Nang"
Place.create! title: "Bus Stop 6", address: "91 Dung Sy Thanh Khe, Da Nang"
Place.create! title: "Bus Stop 7", address: "68 Dung Sy Thanh Khe, Da Nang"

Place.create! title: "Bus Stop 8", address: "399 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 9", address: "261 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 10", address: "200 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 11", address: "28 Kinh Duong Vuong, Da Nang"
Place.create! title: "Bus Stop 12", address: "58 Ly Thai Tong, Da Nang"
Place.create! title: "Bus Stop 13", address: "100 Dung Sy Thanh Khe, Da Nang"
Place.create! title: "Bus Stop 14", address: "44 Dung Sy Thanh Khe, Da Nang"
